# This workflow publishes the package to TestPyPI when code is pushed to dev branch
# Useful for testing releases before publishing to production PyPI

name: Publish to TestPyPI (Dev Branch)

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - '.github/workflows/publish-to-testpypi.yml'
      - 'setup.py'
      - 'MANIFEST.in'
      # Also trigger on version/changelog updates (release preparation)
      - 'CHANGELOG.md'
      - 'README.md'

# Prevent concurrent runs, cancel outdated workflow runs
concurrency:
  group: testpypi-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the distribution packages
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history needed for setuptools-scm

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine setuptools-scm

    - name: Show version (from setuptools-scm)
      run: |
        python -m setuptools_scm
        echo "Version will be automatically determined from git tags"

    - name: Build distribution packages
      run: python -m build

    - name: Check distribution packages
      run: python -m twine check dist/*

    - name: List built packages
      run: ls -lh dist/

    - name: Store distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
        retention-days: 7

  # Publish to TestPyPI
  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for trusted publishing

    steps:
    - name: Download distribution packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip-existing: true  # Don't fail if version already exists
        verbose: true

  # Post-publish verification
  # Full testing matrix to match PyPI verification
  verify-installation:
    name: Verify TestPyPI Installation
    needs: [publish-to-testpypi]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Test on 3 OS with 3 representative Python versions (9 jobs total)
        # Covers: oldest supported, middle, and latest stable
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.11", "3.12"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Wait for TestPyPI to update (120 seconds)
      run: sleep 120
      shell: bash

    - name: Install from TestPyPI
      run: |
        python -m pip install --upgrade pip
        python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pyASDReader
      continue-on-error: true

    - name: Retry installation if failed (TestPyPI might be slow)
      if: failure()
      run: |
        echo "First install attempt failed, waiting 60 more seconds..."
        sleep 60
        python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pyASDReader

    - name: Verify installation
      run: |
        python -c "from pyASDReader import ASDFile; print('Successfully imported ASDFile')"
        python -c "from pyASDReader import __version__; print(f'Package version: {__version__}')"

    - name: Verify package metadata
      run: |
        python -c 'from importlib.metadata import version, metadata; m = metadata("pyASDReader"); pkg_name = m["Name"]; pkg_home = m["Home-page"]; pkg_ver = version("pyASDReader"); print(f"Package: {pkg_name}"); print(f"Location: {pkg_home}"); print(f"Version: {pkg_ver}")'
