# This workflow publishes the package to TestPyPI when code is pushed to dev branch
# Useful for testing releases before publishing to production PyPI

name: Publish to TestPyPI (Dev Branch)

on:
  push:
    branches:
      - dev

# Prevent concurrent runs
concurrency:
  group: testpypi-publish
  cancel-in-progress: false

jobs:
  # Build the distribution packages
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history needed for setuptools-scm

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine setuptools-scm

    - name: Show version (from setuptools-scm)
      run: |
        python -m setuptools_scm
        echo "Version will be automatically determined from git tags"

    - name: Build distribution packages
      run: python -m build

    - name: Check distribution packages
      run: python -m twine check dist/*

    - name: List built packages
      run: ls -lh dist/

    - name: Store distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
        retention-days: 7

  # Publish to TestPyPI
  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download distribution packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip-existing: true  # Don't fail if version already exists
        verbose: true

  # Lightweight verification (only Ubuntu + Python 3.11 to save resources)
  verify-installation:
    name: Verify TestPyPI Installation
    needs: [publish-to-testpypi]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Wait for TestPyPI to update (60 seconds)
      run: sleep 60

    - name: Install from TestPyPI
      run: |
        python -m pip install --upgrade pip
        python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pyASDReader
      continue-on-error: true

    - name: Retry installation if failed
      if: failure()
      run: |
        echo "First install attempt failed, waiting 30 more seconds..."
        sleep 30
        python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pyASDReader

    - name: Verify installation
      run: |
        python -c "from pyASDReader import ASDFile; print('Successfully imported ASDFile')"
        python -c "from pyASDReader import __version__; print(f'Package version: {__version__}')"

    - name: Show installation location
      run: |
        python -c "import pyASDReader; import os; print(f'Installed at: {os.path.dirname(pyASDReader.__file__)}')"
